webtalk_init -webtalk_dir D:/FPGA_Projects/PWM_Module_2/PWM_Module_2.sim/sim_1/behav/xsim/xsim.dir/PWM_Module_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Oct 20 23:27:05 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2348494" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0d03e498-7a5a-41f1-9931-ce40f52debaa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5692fa72334c41ea8078f696a1cf3ebf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "50" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14168_KB" -context "xsim\\usage"
webtalk_transmit -clientid 396990973 -regid "" -xml D:/FPGA_Projects/PWM_Module_2/PWM_Module_2.sim/sim_1/behav/xsim/xsim.dir/PWM_Module_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/FPGA_Projects/PWM_Module_2/PWM_Module_2.sim/sim_1/behav/xsim/xsim.dir/PWM_Module_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/FPGA_Projects/PWM_Module_2/PWM_Module_2.sim/sim_1/behav/xsim/xsim.dir/PWM_Module_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
